"""empty message

Revision ID: 16f5428ae870
Revises: b8682a94f391
Create Date: 2022-04-23 15:29:24.130607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f5428ae870'
down_revision = 'b8682a94f391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuito', sa.Column('description', sa.String(length=200), nullable=False))
    op.add_column('circuito', sa.Column('image', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'circuito', ['description'])
    op.add_column('moto', sa.Column('description', sa.String(length=200), nullable=False))
    op.add_column('moto', sa.Column('image', sa.String(length=200), nullable=False))
    op.add_column('moto', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moto', 'price')
    op.drop_column('moto', 'image')
    op.drop_column('moto', 'description')
    op.drop_constraint(None, 'circuito', type_='unique')
    op.drop_column('circuito', 'image')
    op.drop_column('circuito', 'description')
    # ### end Alembic commands ###
