"""empty message

Revision ID: 3a0c1096c597
Revises: ec5f7b416c63
Create Date: 2023-02-10 17:03:36.212407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0c1096c597'
down_revision = 'ec5f7b416c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('moto_reserve_id_fkey', 'moto', type_='foreignkey')
    op.drop_column('moto', 'reserve_id')
    op.add_column('reserve', sa.Column('moto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reserve', 'moto', ['moto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserve', type_='foreignkey')
    op.drop_column('reserve', 'moto_id')
    op.add_column('moto', sa.Column('reserve_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('moto_reserve_id_fkey', 'moto', 'reserve', ['reserve_id'], ['id'])
    # ### end Alembic commands ###
