"""empty message

Revision ID: 558307e8480b
Revises: 16f5428ae870
Create Date: 2022-04-23 15:55:05.095621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558307e8480b'
down_revision = '16f5428ae870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circuito', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circuito', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
