"""empty message

Revision ID: 5e0e98a43aac
Revises: b9075262a9ff
Create Date: 2022-05-19 21:32:33.951379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0e98a43aac'
down_revision = 'b9075262a9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_user_id_fkey', 'profile', type_='foreignkey')
    op.drop_column('profile', 'user_id')
    op.add_column('user', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'profile_id')
    op.add_column('profile', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('profile_user_id_fkey', 'profile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
