"""empty message

Revision ID: 5ef5a903cc9c
Revises: 3a0c1096c597
Create Date: 2023-02-10 17:42:03.089000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef5a903cc9c'
down_revision = '3a0c1096c597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reserve_reservation_date_key', 'reserve', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('reserve_reservation_date_key', 'reserve', ['reservation_date'])
    # ### end Alembic commands ###
