"""empty message

Revision ID: b8682a94f391
Revises: a4c324a54286
Create Date: 2022-04-23 15:00:21.303164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8682a94f391'
down_revision = 'a4c324a54286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('circuito_user_id_fkey', 'circuito', type_='foreignkey')
    op.drop_column('circuito', 'user_id')
    op.add_column('moto', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'moto', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moto', type_='foreignkey')
    op.drop_column('moto', 'user_id')
    op.add_column('circuito', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('circuito_user_id_fkey', 'circuito', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
