"""empty message

Revision ID: b891b1d6ab50
Revises: 3859b982fb21
Create Date: 2022-05-14 14:03:29.947332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b891b1d6ab50'
down_revision = '3859b982fb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circuito', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.add_column('moto', sa.Column('stripe_id', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moto', 'stripe_id')
    op.alter_column('circuito', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
