"""empty message

Revision ID: f55d54f894e3
Revises: d733d65fbfbd
Create Date: 2022-05-05 21:12:11.923976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55d54f894e3'
down_revision = 'd733d65fbfbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moto', sa.Column('reserve_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'moto', 'reserve', ['reserve_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moto', type_='foreignkey')
    op.drop_column('moto', 'reserve_id')
    # ### end Alembic commands ###
